CREATE TABLE IF NOT EXISTS BRAND(
  BRAND_ID INT NOT NULL,
  NAME varchar(100),
  PRIMARY KEY (BRAND_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT(
  PRODUCT_ID INT NOT NULL,
  NAME varchar(100),
  PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS PRICES(
  PRICE_LIST INT NOT NULL,
  BRAND_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  START_DATE TIMESTAMP,
  END_DATE TIMESTAMP,
  PRIORITY INT,
  PRICE numeric(10,2),
  CURR varchar(50),
  PRIMARY KEY (PRICE_LIST),
  FOREIGN KEY (PRODUCT_ID) references PRODUCT,
  FOREIGN KEY (BRAND_ID) references BRAND
);
